apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    tier: {{ .Values.service.tier }}
    release: {{ .Release.Name }}
spec:
  strategy:
      type: Recreate
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }} 
      tier: {{ .Values.service.tier }} 
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        tier: {{ .Values.service.tier }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: {{ .Chart.Name }}
          containerPort: 80
        #resources: 
#{{ toYaml .Values.resources | indent 10 }}
