apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    tier: {{ .Values.service.tier }}
    release: {{ .Release.Name }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.internalPort }}
      targetPort: {{ .Values.service.externalPort }}
      nodePort: {{ .Values.service.nodeport }}
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    tier: {{ .Values.service.tier }}
