apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    tier: {{ .Values.service.tier }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        tier: {{ .Values.service.tier }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        #volumeMounts:
        #- mountPath: /opt/service-bind
        #  name: service-bind-volume
        ports:
        - name: http
          containerPort: {{ .Values.service.internalPort }}
        #env:
        #- name: svcbindingmountpath
        #  value: /opt/service-bind
        resources: 
{{ toYaml .Values.resources | indent 10 }}
      #volumes:
      #- name: service-bind-volume
      #  secret:
      #    defaultMode: 420
      #    secretName: binding-arpittestvisualrecognition-m2
