# Default values for lets-chat.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: arprasto/userinfoicphelmchart
  tag: v1
  pullPolicy: Always
service:
  name: icphelmchart
  tier: frontend
  type: NodePort
  internalPort: 6001
  externalPort: 6001
  nodeport: 31000
resources:
  limits:
    memory: 512Mi
  requests:
    memory: 128Mi
