# Default values for lets-chat.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: arprasto/userinfohelmchart
  tag: v1
  pullPolicy: Always
service:
  name: userinfoicphelmchart
  tier: frontend
  type: NodePort
  protocol: TCP
  internalPort: 8080
  externalPort: 8080
  nodeport: 30091
resources:
  limits:
    memory: 512Mi
  requests:
    memory: 128Mi
